### ISSUE TITLE
:globe_with_meridians: Implement k-means algorithm

### ISSUE THREAD

**Issue by Thomaltarix** [Thomaltarix/ImageCompressor#5]
# :white_check_mark: What's needed
You must implement the main algorithm of the project.

This algorithm is the `k-means`. It consists of regrouping pixels by k *(given in the file)* clusters according to the color differences.
Until the clusters movements are less than the given convergence, the program must compute new bunch of k clusters and add data to its nearest clusters.

The computation works with color distance *(so distance between color vectors)*. Here's a simple equation to compute it:

![image](https://github.com/Thomaltarix/ImageCompressor/assets/114673563/614bac10-70c0-4183-a04a-1ef994912f94)

*Convergence is considered reached when all the clusters have moved less than the convergence parameter since the last
iteration.*

## 📋 Subtasks
- [x] Build the convergence loop
- [x] Make the creation of the clusters 
- [x] Compute the color distance for each iteration
- [x] Display the asked output *(see below)* at the end of the convergence loop

![image](https://github.com/Thomaltarix/ImageCompressor/assets/114673563/993e4f22-5820-4417-8e53-811b467e6d17)

The output is formatted like this:
```
--
Cluster color vector1 -> (r,g,b)
-
Cluster linked color vector1 -> (r,g,b)
Cluster linked color vector2 -> (r,g,b)
Cluster linked color vector3 -> (r,g,b)
--
Cluster color vector2 -> (r,g,b)
-
...
```
## :file_folder: Files required
*List all required files if any*
