### ISSUE TITLE
:monocle_face: Parse the given file

### ISSUE THREAD

**Issue by Thomaltarix** [Thomaltarix/ImageCompressor#9]
# :white_check_mark: What's needed
You must parse the file given in the `-f` option and return an appropriate data type.
Here's an exemple of a given file:

![image](https://github.com/Thomaltarix/ImageCompressor/assets/114673563/ac43635c-a05b-447b-9750-cfa5c1f4d230)

To parse it, there's some steps detailed below.

## 📋 Subtasks
- [ ] Read the list of pixels from the file passed as argument, according to the following grammar (x,y) (r,g,b) *(See an exemple above)*
- [ ] Return `Conf` data type which contains list of vectors. Each vector contains its coordinates and its color.
- [ ] Handle the errors from the given file.

## :file_folder: Files required
- [ ] `FileParsing.hs`
